# Generated by Django 5.2.4 on 2025-07-13 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0031_alter_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
