# Generated by Django 5.2.4 on 2025-07-13 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0032_prescriptionitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price per unit at time of prescription', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
