# Generated by Django 5.2.4 on 2025-07-15 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0033_remove_prescriptionitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='current_balance',
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit at time of prescription', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
